import React, { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { connect } from 'react-redux';

function Index() {
    const [loading, setLoading] = useState(true);
    
    return (
        <main className={styles.main}>
            <Head>
                <title>Simple Quicks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="#" />
            </Head>
            
        </main>
    )
}

const mapStateToProps = (state) => ({
    
});

const mapDispatchToProps = {
    
};

export default connect(mapStateToProps, mapDispatchToProps)(Index);
