import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { connect } from 'react-redux';
import dynamic from 'next/dynamic';
import SplashScreen from '@/utils/splash-screen';

function Index() {
  const theme = 'light-theme';
  const MainTheme = dynamic(() => import(`@/themes/${theme}`));
  const [splashScreen, setSplashScreen] = useState(true);

    useEffect(() => {
        setTimeout(() => {
            setSplashScreen(false);
        }, 3000);
    }, [splashScreen]);
    
    return (
        <React.Fragment>
            <Head>
                <title>Simple Quicks | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./Icons/Favicon.png" />
            </Head>
            {splashScreen ? (
                <SplashScreen/>
            ) : (
              <MainTheme/>
            )}
        </React.Fragment>
    )
}

const mapStateToProps = (state) => ({
    
});

const mapDispatchToProps = {
    
};

export default connect(mapStateToProps, mapDispatchToProps)(Index);