import React, { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/light.module.css';
import { connect } from 'react-redux';
import Drawer from '@/themes/light-theme/components/drawer';

function Index() {
    
    return (
        <main className={styles.main}>
            <Head>
                <title>Simple Quicks | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./Icons/Favicon.png" />
            </Head>
            <Drawer/>
        </main>
    )
}

const mapStateToProps = (state) => ({
    
});

const mapDispatchToProps = {
    
};

export default connect(mapStateToProps, mapDispatchToProps)(Index);